spring:
  cloud:
    ## Enable the gateway
    gateway:
      enabled: true
      ## Declare the routes
      routes:
        ## Users MicroServices routes
        - id: USERS
          uri: lb://MS-USERS
          predicates:
            - Path=/api/users/**
        ## Users-Entitlement Microservices routes
        - id: USERS-ENTITLEMENT
          uri: lb://MS-USERS-ENTITLEMENT
          predicates:
            - Path=/api/entitlement/**

eureka:
  ## Register as a client to the Eureka server
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: "http://eureka:8761/eureka"

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"