server:
  ## Declare the port for the Gateway
  port: 9090
spring:
  ## Declaring the default and active profiles
  profiles:
    default: dev
    active: dev
  ## Declare the Application name
  application:
    name: ms-gateway
  output:
    ansi:
      enabled: ALWAYS

application:
  version: @project.version@