
spring:
  ## Declaring the default and active profiles
  profiles:
    default: dev
    active: dev
  ## Declare the Application name
  application:
    name: ms-gateway

eureka:
  ## Register as a client to the Eureka server
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true

application:
  version: @project.version@