server:
  ## Declare the port for the Gateway
  port: 9090

spring:
  cloud:
    ## Enable the gateway
    gateway:
      enabled: true
      ## Declare the routes
      routes:
        ## Users MicroServices routes
        - id: USERS
          uri: lb://MS-USERS
          predicates:
            - Path=/api/users/**
        ## Users-Entitlement Microservices routes
        - id: USERS-ENTITLEMENT
          uri: lb://MS-USERS-ENTITLEMENT
          predicates:
            - Path=/api/entitlement/**
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"